### ISSUE TITLE
Delegate keyResolver shoud be able to use the method name.

### ISSUE THREAD

**Issue by tripodsgames** [vlio20/utils-decorators#113]
Currently only 1 `@delegate` can be used per class at a time, if i use something like Promise.all and call multiple methods the application crash.

**Comment by vlio20** [comment]
Hi @tripodsgames can you please share a code example?

**Comment by tripodsgames** [comment]
> Hi @tripodsgames can you please share a code example?

Sure!

If you run 2 delegates on the same class at the same time, they will throw:
 `ERROR Error: Uncaught (in promise): TypeError: can't access property "ex2", this is undefined`

```typescript

class Example {
  @delegate()
  async ex1() {
    return this.ex2();
  }

  @delegate()
  async ex2() {
    return 2;
  }
}

class AnotherClass {
  async run() {
    const ex = new Example();
    const result = await ex.ex1();
    console.log(result);
  }
}

// ...
new AnotherClass().run();

```

A fix would be to use the class and method name in key resolver.
I believe the same problem may be happening in other decorators.

**Comment by vlio20** [comment]
Checking it out.

**Comment by vlio20** [comment]
@vlio20 I found the issue you can follow the progress in the following PR: https://github.com/vlio20/utils-decorators/pull/114

I will create a release as soon as the CI will pass.

**Comment by vlio20** [comment]
@tripodsgames please try version 1.10.1
Let me know if it works for you

**Comment by tripodsgames** [comment]
> @tripodsgames please try version 1.10.1
> Let me know if it works for you

Problem fixed! Thanks.

**Comment by vlio20** [comment]
@tripodsgames thanks for raising the issue. I will really appreciate if you will a ⭐ to this repo.

**Comment by tripodsgames** [comment]
> @tripodsgames thanks for raising the issue. I will really appreciate if you will a star to this repo.
I already did it.

**Comment by vlio20** [comment]
thanks a lot!! enjoy.
