### ISSUE TITLE
Cache burst for memoize/memoizeAsync

### ISSUE THREAD

**Issue by rdhainaut** [vlio20/utils-decorators#124]
First, thanks for your work and this library.

Please is it possible to provide a sample how to "burst"/invalidate the cache when we use memoize/memoizeAsync function/decorator ? 

Thank you

**Comment by vlio20** [comment]
hi @rdhainaut, for both decorators you can pass your own cache object (see here https://vlio20.github.io/utils-decorators/#memoize) under the cache attribute of the config object. That way you can control the cache as you wish. Does it helps?

**Comment by masoud-msk** [comment]
Extending your 2nd solution, you can already use `@after`
```ts
class LikeCounter {
  cache = new Map<string, number>();
  
  @memoizeAsync({ cache })
  public async FetchLikesCount(): Promise<number> { }
  
  @after({
    func: () => cache.delete('FetchLikesCount'),
    wait: true,
  })
  public async IncrementLikesCount() { }
}
```
Note that `IncrementLikesCount`'s input and output are also available to `@after`'s `func` option if you have a more complex case.

**Comment by vlio20** [comment]
Closing for now as @masoud-msk suggested a good solution IMO
