### ISSUE TITLE
Disable Caching for test envs

### ISSUE THREAD

**Issue by Nemo9439** [vlio20/utils-decorators#138]
I'm using @memoizeAsync , and it tends screw up my unit tests , 
as the result of one test is being cached and returned in another test.

I want a simple way to disable caching globally in order to avoid this.

**Comment by vlio20** [comment]
@Nemo9439 any suggestions?

**Comment by tripodsgames** [comment]
> @Nemo9439 any suggestions?

@vlio20
I'm testing a branch with a global configuration object, so we can modify the settings at a global level.
EX:
```ts
Config.Global.disableCache = true;
```
I want your opinion on this

**Comment by vlio20** [comment]
@tripodsgames, I would like to avoid that because of the different configuration options that the different decorators have. Any other suggestions?

**Comment by tripodsgames** [comment]
> @tripodsgames, I would like to avoid that because of the different configuration options that the different decorators have. Any other suggestions?

And a base configuration per decorator?
EX:
```ts
memoizeAsync.DefaultSettings.disableCache = true;
```

It would even be useful to configure a default configuration.
EX:
```ts
memoizeAsync.DefaultSettings.expirationTimeMs = 10000;
```

**Comment by vlio20** [comment]
I think it would be better to have such configuration on the app level and not inside the lib. As there are multiple ways in which you could provide the configuration to the different decorators.

As more as I am thinking about a global configuration the less I want it to be part of the lib.

**Comment by scaljeri** [comment]
This issue is already old, maybe it should be closed. But anyway, my suggestion to @Nemo9439 is to write a wrapper decorator which does what he needs. I did something similar in [this](https://stackblitz.com/edit/typescript-dp3kfv?file=index.ts,cache-decorator.ts,cache-param-ignore.ts) stackblitz
