### ISSUE TITLE
debounce should support multi instances

### ISSUE THREAD

**Issue by Shemesh** [vlio20/utils-decorators#145]
hi,
the debounce decorator does not support multi instances.
plz read this article - https://engineering.datorama.com/be-aware-of-the-debounce-decorator-6fb24a6d8d5
and here is the solution -https://github.com/NetanelBasal/helpful-decorators/blob/master/src/debounce.ts

**Comment by vlio20** [comment]
@Shemesh would you mind submitting a PR?

**Comment by vlio20** [comment]
The issue reproduced on stackblitz: 
https://angular-3bpkw9.stackblitz.io

**Comment by vlio20** [comment]
Will be available in 2.0.5
fixed in #146
