### ISSUE TITLE
Using with regular Node.js v20 or v22

### ISSUE THREAD

**Issue by robogeek** [vlio20/utils-decorators#174]
Your documentation says:

> Please note that the decorators are working perfectly with plain JavaScript code as well as with TypeScript.

But, I have installed them for a Node.js (not TypeScript) project, and copied one of your example class decorations into a source file:

```js

import { after } from 'utils-decorators';

class Example1 {

    @after({
      func: 'after',
    })
    foo(x /*: number */) /*: number */ {
      return 42;
    }

    after(respData/*: AfterParams<number>*/) /*: void*/ {
      console.log(respData.args, respData.response);
    }
}
```

The code is contained within an ESM module (file name ends in `.mjs`).  I commented out the TypeScript types stuff because this is plain JavaScript, just as your documentation says.

Running this file gives the following error:

```shell
file:///home/david/Projects/akasharender/akasharender/cache/file-cache-sqlite.mjs:15
    @after({
    ^

SyntaxError: Invalid or unexpected token
    at compileSourceTextModule (node:internal/modules/esm/utils:340:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:102:18)
    at #translate (node:internal/modules/esm/loader:433:12)
    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:480:27)
    at async ModuleJob._link (node:internal/modules/esm/module_job:112:19)

Node.js v22.11.0
```

I'm getting the exact same error when trying to use sqlite3orm: https://github.com/gms1/HomeOfThings/issues/17

**Comment by vlio20** [comment]
there is no support of decorators in pure js yet. But you can use the underline functions that are used by the decorators. For example @after -> afterify 
https://vlio20.github.io/utils-decorators/#after
