### ISSUE TITLE
please add code samples

### ISSUE THREAD

**Issue by born2net** [vlio20/utils-decorators#93]
please add code samples

**Comment by vlio20** [comment]
@born2net what tyoe of code samples? Just examples of how to use the decorator?

**Comment by born2net** [comment]
for example ```@memoizeAsync ``` code snipper for usage will be helpful.
thanks!

**Comment by vlio20** [comment]
I will add examples in the Readme file in the near future. Meanwhile I suggest you to take examlles from my blog post about this specific decorator: https://link.medium.com/AfVimxI1Tab

Let me know if it is helpful.

**Comment by born2net** [comment]
or for example ```@retry({retries: 1, delay: 1})`` is erroring on 

```
Error:(179, 5) TS1241: Unable to resolve signature of method decorator when called as an expression.
  Type 'TypedPropertyDescriptor<AsyncMethod<any>>' is not assignable to type 'TypedPropertyDescriptor<(e: any) => boolean>'.
    Type 'AsyncMethod<any>' is not assignable to type '(e: any) => boolean'.
      Type 'Promise<any>' is not assignable to type 'boolean'.
```
so sample snippets will be helpful.
tx

**Comment by born2net** [comment]
great will check blog

**Comment by vlio20** [comment]
@born2net can you show the full example of the retry decorator?

**Comment by born2net** [comment]
![image](https://user-images.githubusercontent.com/5090936/97204463-57ffec80-1773-11eb-83a6-f58eb4fa61c9.png)

**Comment by vlio20** [comment]
Are you sure that this method returning a promise in all scenarios?

**Comment by born2net** [comment]
oh... didn't realize need to return a Promise. Ok I will fix no worries, thus an snippet code example would be helpful as I could see it in the demo. tx again, Sean.

**Comment by vlio20** [comment]
Np
